// Texto plano de la aplicación, ordenado alfabéticamente
export const keys: Record<string, string> = {
    actions: 'Acciones',
    avatar: 'Avatar',
    carouselLeft: 'chevron_left',
    carouselRight: 'chevron_right',
    closeSession: '¿Está seguro de cerrar la sesión?',
    continue: 'Continuar',
    createUser: 'Crear Usuario',
    questionDeleteHero: '¿Está seguro de eliminar al super héroe?',
    edit: 'Editar',
    heroesCreateRoute: '/heroesCreate',
    heroesEditRoute: '/heroesEdit',
    heroesListRoute: '/heroesList',
    heroDelete: 'Eliminar héroe',
    heroEdited: 'Super héroe editado con éxito',
    heroEdit: 'Editar héroe',
    heroCreated: 'Super héroe creado',
    heroDeleted: 'El super héroe fue eliminado',
    heroFour: '../../assets/Images/Heroes/8.png',
    heroName: 'Apodo de Superhéroe',
    heroOne: '../../assets/Images/Heroes/5.png',
    heroThree: '../../assets/Images/Heroes/7.png',
    heroTwo: '../../assets/Images/Heroes/6.png',
    invisibility: 'Invisibilidad',
    login: 'Iniciar Sesión',
    maxCharacters: 'Máximo 15 caracteres',
    maxHeroes: 'Has creado el máximo de héroes permitidos',
    modalWidth: '350px',
    name: 'Nombre Real',
    noHeroes: 'No hay héroes en la Guarida secreta',
    noHeroesToEdit: 'No hay héroes para editar',
    noResults: 'No hay resultados',
    power: 'Poder',
    register: 'Registrar',
    search: 'search',
    secretLair: 'Guarida secreta',
    selectAvatar: 'Selecciona avatar',
    superDesign: 'Super diseña',
    superSpeed: 'Super velocidad',
    superStrength: 'Super fuerza',
    ultraInstinct: 'Ultrainstinto',
    userCreated: 'Usuario creado',
    userNoExists: 'El usuario no existe',
    userUpperCase: 'El nombre debe comenzar con una letra mayúscula.',
    weakness: 'Debilidad',
    yes: 'Sí',
    no: 'No'
};